import vue from "@vitejs/plugin-vue";
import path from "node:path";
import { defineConfig } from "vitest/config";

// Deliberately a SEPARATE config from vite.config.ts.
//
// The app config pulls in VitePWA, vue-devtools and copySpessaSynthWorklet().
// That last one throws from `configResolved` when node_modules is incomplete and
// writes into public/ on every startup — neither of which belongs in a test run.
// Tests only need the Vue SFC compiler and the `@` alias.
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  test: {
    environment: "happy-dom",
    globals: true,
    setupFiles: ["./test/setup.ts"],
    include: ["src/**/*.{test,spec}.ts", "test/**/*.{test,spec}.ts"],
    // test/known-issues/** asserts behaviour the app does NOT yet have, so it
    // is expected to fail and lives in its own run (vitest.known-issues.config.ts,
    // `pnpm test:known-issues`). Keeping it out of the main suite is what lets
    // "red" here keep meaning "you just broke something".
    exclude: ["**/node_modules/**", "**/dist/**", "test/known-issues/**"],
    // Pinned so tests never depend on the developer's local .env and can assert
    // on fully-built request URLs.
    env: {
      VITE_PUBLIC_DIRECTUS_URL: "https://directus.test",
    },
    // Every test starts from a clean slate: spies restored to originals and any
    // vi.stubGlobal / vi.stubEnv undone.
    restoreMocks: true,
    unstubEnvs: true,
    unstubGlobals: true,
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      reportsDirectory: "./coverage",
      // Scoped to the logic layer this suite actually targets. Including the
      // view/component tree would bury a meaningful number under thousands of
      // untested template lines and make the percentage useless as a signal.
      // Components are better served by e2e coverage than by unit mounting.
      include: [
        "src/composables/**/*.ts",
        "src/stores/**/*.ts",
        "src/lib/**/*.ts",
        "src/router/**/*.ts",
        "src/plugins/**/*.ts",
      ],
      exclude: [
        // Generated by graphql-codegen — not our logic to test.
        "src/gql/**",
        "src/**/*.d.ts",
      ],
      // Thresholds sit a few points under the current actuals: routine churn
      // will not break the build, but a real regression will.
      //
      // The global line/statement figure is held down by useMidiPlayer.ts
      // (1138 lines, 0%). It is deliberately untested — it runs
      // refreshOutputsShared() at import time and needs Web MIDI, AudioContext
      // and AudioWorklet, so unit tests would mostly assert against mocks.
      // It is left IN the report rather than excluded, so the gap stays
      // visible instead of being hidden behind a flattering number.
      thresholds: {
        lines: 78,
        statements: 78,
        branches: 90,
        functions: 88,
        perFile: false,

        // The offline-first auth contract — a silent regression here strands a
        // user at /login mid-service, which is the worst failure this app has.
        "src/composables/useAuth.ts": {
          lines: 92,
          statements: 92,
          branches: 85,
          functions: 100,
        },
        "src/stores/auth.ts": {
          lines: 98,
          statements: 98,
          branches: 92,
          functions: 100,
        },
        // Capped at 94.28: the catch blocks at lines 93-94 and 106-107 are
        // unreachable, because getTokenExpiry() already swallows every error
        // and returns 0 rather than throwing.
        //
        // branches raised from 82 to 85 when issue #11 was fixed: the
        // missing-`exp` path used to be asserted only in
        // test/known-issues/issue-11-jwt-missing-exp.test.ts, which coverage
        // does not measure. That spec is now a regression guard in
        // test/composables/useJwtUtils.test.ts, so the branch is measured again.
        "src/composables/useJwtUtils.ts": {
          lines: 94,
          statements: 94,
          branches: 85,
          functions: 100,
        },
        // The offline download/IndexedDB layer.
        "src/composables/useOfflineDownload.ts": {
          lines: 98,
          statements: 98,
          branches: 92,
          functions: 85,
        },
        // functions is low by construction: every `component: () => import(...)`
        // route entry counts as a function and most are never invoked.
        "src/router/index.ts": {
          lines: 95,
          statements: 95,
          branches: 95,
          functions: 60,
        },
      },
    },
  },
});
